#!/bin/bash

function get-servers {
  SERVERS=$(curl -s -H "Authorization: Bearer $HAPI" https://api.hetzner.cloud/v1/servers \
    | jq '.servers[] | .id')
}

function get-server-ips {
  IPS=$(curl -s -H "Authorization: Bearer $HAPI" https://api.hetzner.cloud/v1/servers \
    | jq '[.servers[] | .public_net.ipv4.ip] | join(",")' | tr -d '"')
}

function remove-all {
  get-servers
  for serv in $SERVERS; do
    serv=`echo $serv | tr -d '"'`
    curl -s -X DELETE -H "Authorization: Bearer $HAPI" https://api.hetzner.cloud/v1/servers/$serv
  done
}

function create-all {
TYPE=cx11
IMAGE=ubuntu-16.04
SSHKEY=emanaev@host
NAME=node

for i in $(seq 1 $1)
do

  curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $HAPI" \
    -d "{\"name\": \"$NAME$i\", \"server_type\": \"$TYPE\", \"start_after_create\": true, \"image\": \"$IMAGE\", \"ssh_keys\": [\"$SSHKEY\"]}" \
    https://api.hetzner.cloud/v1/servers
done

}

case $1 in
  remove-all)
    remove-all
  ;;
  create-all)
    create-all 3
    get-server-ips
    echo $IPS
  ;;
  ips)
    get-server-ips
    echo $IPS
  ;;
  *)
esac
