

kube_network_plugin: weave

kube_proxy_mode: iptables

#deploy_netchecker: true

helm_enabled: true

ingress_nginx_enabled: true
cert_manager_enabled: true

local_volume_provisioner_enabled: true
local_volume_provisioner_namespace: kube-system
local_volume_provisioner_storage_classes:
  local-storage:
    host_dir: /mnt
    mount_dir: /mnt/disks
